"""empty message

Revision ID: fa1c8114fcba
Revises: f9391a4dc544
Create Date: 2026-06-04 18:23:51.289097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1c8114fcba'
down_revision = 'f9391a4dc544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reviews_recipe_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('reviews_user_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('reviews_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('reviews_recipe_id_key'), ['recipe_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
